NDefines.NNationDesigner.MANDATE_SUBCONTINENT_NAME = "ranasiu_superregion"
NDefines.NCountry.CIRCUMNAVIGATION_PROVINCE_1 = 3700
NDefines.NCountry.CIRCUMNAVIGATION_PROVINCE_2 = 3518
NDefines.NCountry.CIRCUMNAVIGATION_PROVINCE_3 = 3330
NDefines.NCountry.CIRCUMNAVIGATION_PROVINCE_4 = 3547
NDefines.NCountry.CIRCUMNAVIGATION_PROVINCE_5 = 3242
NDefines.NCountry.CIRCUMNAVIGATION_PROVINCE_6 = 3316
